# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13741e7c4924eae734c9dc515c6210195be9583df3da5b6dde89399f56c4a6be0102bb8517e41fed00ba08a9aa7edf6cd63fde36a3a3ecc0d155df9d2c47cc3a

test:
  secret_key_base: 3bc9acda9832eb2c3eef4d8f94e762363a80b9c9d3a2f65ed395b320ad82e80aa366a577f27adef9175833838b70d22c601c32f49d3a50511cc2dc03804f7785

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
